name: ZIP Resource Pack

on:
  push:
    branches:
      - '*'
  workflow_dispatch:

jobs:
  create-zip:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Get timestamp
        id: timestamp
        run: echo "timestamp=$(date +'%Y%m%d_%H%M%S')" >> $GITHUB_OUTPUT
      
      - name: Get short SHA
        id: sha
        run: echo "sha=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
      
      - name: Create zip archive
        run: |
          zip -r "repo_${{ steps.timestamp.outputs.timestamp }}_${{ steps.sha.outputs.sha }}.zip" 
      - name: Upload zip artifact
        uses: actions/upload-artifact@v4
        with:
          name: repository-archive
          path: "repo_${{ steps.timestamp.outputs.timestamp }}_${{ steps.sha.outputs.sha }}.zip" 
